encoder_path: "ace/ace_encoder_pretrained.pt"
num_head_blocks: 1
learning_rate_min: 0.0005
learning_rate_max: 0.005
training_buffer_size: 8000000
samples_per_image: 1024
batch_size: 5120
epochs: 16
repro_loss_hard_clamp: 1000
repro_loss_soft_clamp: 50
repro_loss_soft_clamp_min: 1
use_half: true
use_homogeneous: true
use_aug: true
aug_rotation: 15
aug_scale: 1.5
image_resolution: 384
repro_loss_type: "dyntanh"  # ["l1", "l1+sqrt", "l1+log", "tanh", "dyntanh"]
repro_loss_schedule: "circle"
depth_min: 0.1
depth_target: 10
depth_max: 1000
num_clusters: null
cluster_idx: null
render_visualization: false
render_target_path: "renderings"
render_flipped_portrait: false
render_map_error_threshold: 10
render_map_depth_filter: 10
render_camera_z_offset: 4
